# Generated by Django 3.2.8 on 2021-10-28 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('task_description', models.TextField()),
            ],
        ),
    ]
