# Generated by Django 3.2.8 on 2021-10-28 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='choices',
            field=models.CharField(choices=[('NC', 'Not Completed'), ('C', 'Completed')], default='NC', max_length=2),
        ),
    ]
