# Generated by Django 3.2.8 on 2021-10-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='choices',
            new_name='status',
        ),
    ]
