# Generated by Django 3.2.8 on 2021-10-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_choices_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('TY', 'Task'), ('CN', 'Chore')], default='TY', max_length=2),
        ),
    ]
