# Generated by Django 3.2.8 on 2021-10-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Task', 'Task'), ('Chore', 'Chore')], default='Task', max_length=5),
        ),
    ]
