# Generated by Django 3.2.8 on 2021-11-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20211102_1941'),
    ]

    operations = []
