# Generated by Django 3.2.8 on 2021-11-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
