# Generated by Django 3.2.8 on 2021-11-02 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_task_description'),
    ]

    operations = [

    ]
